#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and 4th loop iteration display bad luck and on 8th display good luck
n=1
while [ $n -le 10 ]
do 
  if [ $n = 4 ]
  then 
      echo "bad luck"
  elif [ $n = 8 ]
  then 
     echo "good luck"
  else
     echo "Best School"
  fi
  ((n++))
done
